### ISSUE TITLE
pip install fails on windows (2.7 x32)

### ISSUE THREAD

**Issue by valhallasw** [repoze/repoze.lru#23]
The install works, but `C:\Python27\Lib\site-packages\repoze\__init__.py` is not installed, which causes `import repoze.lru` to fail with `ImportError: No module named repoze.lru`.

Creating an empty file `C:\Python27\Lib\site-packages\repoze\__init__.py` solves the issue, but I'd say setup.py should not skip installing the **init**.py.

pip install log:

```
...>pip install repoze.lru
Downloading/unpacking repoze.lru
  Downloading repoze.lru-0.6.tar.gz
  Running setup.py (path:c:\users\...\appdata\local\temp\pip_build_deen\repoze.lru\setup.py) egg_info for package repoze.lru

Installing collected packages: repoze.lru
  Running setup.py install for repoze.lru

    Skipping installation of C:\Python27\Lib\site-packages\repoze\__init__.py (namespace package)
    Installing C:\Python27\Lib\site-packages\repoze.lru-0.6-py2.7-nspkg.pth
Successfully installed repoze.lru
Cleaning up...
```

**Comment by tseaver** [comment]
@valhallasw `pip` / `setuptools` have had recurring issues with installing namespace packages.  Please feel free to re-open if you can reproduce with current versions of the two.
